Repository wecode-bootcamp-korea/26-2nd-Weterest-backend, pull requests merged in 2021-11, with the labels that each got.

#1 Create: Modeling 결과 models.py 생성 및 migrations
  boards/__init__.py
  boards/admin.py
  boards/apps.py
  boards/migrations/0001_initial.py
  boards/migrations/0002_initial.py
  boards/migrations/__init__.py
  boards/models.py
  boards/tests.py
  boards/views.py
  config/settings.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 수정 요청

#3 Modified: models.py in users and boards
  boards/__init__.py
  boards/admin.py
  boards/apps.py
  boards/migrations/0001_initial.py
  boards/migrations/0002_initial.py
  boards/migrations/__init__.py
  boards/models.py
  boards/tests.py
  boards/views.py
  config/settings.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#4 Add: BoardListView for mainpage, detailpage, searchbar
  boards/models.py
  boards/tests.py
  boards/urls.py
  boards/views.py
  config/settings.py
  config/urls.py
  requirements.txt
Labels: Status: Accepted

#6 [권상현] UPDATE : create new column(login_platform_id) in users.models
  users/migrations/0002_user_login_platform_id.py
  users/models.py
Labels: Status: 리뷰 요청

#7 [권상현] 로그인 데코레이터 기능
  config/settings.py
  config/urls.py
  core/utils.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#9 Add: post method for create board in BoardListView
  .gitignore
  boards/tests.py
  boards/views.py
  config/settings.py
  requirements.txt
Labels: Status: 리뷰 요청

#8 [권상현] ADD : Pined Boards display in mypage
  boards/tests.py
  boards/urls.py
  boards/views.py
  config/settings.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#10 [장재원] Add : MyBoardView for create board in mypage
  boards/tests.py
  boards/urls.py
  boards/views.py
Labels: Status: 리뷰 요청

#12 [권상현] ADD : Pin on pictures interested in
  boards/tests.py
  boards/urls.py
  boards/views.py
Labels: Status: 리뷰 요청

#11 Add: BoardDetailView for detail page
  boards/tests.py
  boards/urls.py
  boards/views.py
Labels: Status: 리뷰 요청

#13 Add: DockerFile & requirement.txt fixed
  Dockerfile
  requirements.txt
Labels: Status: 리뷰 요청

#15 [권상현] FIX : Django error
  boards/tests.py
  boards/views.py
Labels: Status: 리뷰 요청

#16 Modified:DockerFile and Publish Done in EC2, RDS
  Dockerfile
  requirements.txt
Labels: Status: 리뷰 요청
